name: forest_tagger
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.0
  sqflite: ^2.3.0
  mapbox_gl: ^0.16.0
  shadow_clip: ^0.0.1
  uuid: ^4.3.2
  toast: ^0.3.0
  geolocator: ^10.1.0
  path_provider: ^2.1.2
  screenshot: ^2.1.0
  permission_handler: ^11.1.0
  pdf: ^3.8.4
  randomstring_dart: ^0.0.4
  pretty_qr_code: ^3.0.0
  sign_in_button: ^3.2.0
  auth_buttons: ^3.0.2
  image_picker: ^1.0.7
  barcode_scan2: ^4.3.0
#   barcode_scan: ^2.0.1
#   pretty_qr_code: ^1.0.1
#   uuid: 2.2.2
#   sqflite: ^1.3.0
#   random_string: ^2.1.0
#   firebase_analytics:
#   cloud_firestore:
#   firebase_auth:
#   firebase_core:
#   screenshot: ^0.3.0
#   permission_handler: ^5.1.0+2
#   pdf: ^2.1.0
#   downloads_path_provider: ^0.1.0
#   path_provider:
#   toast:
#   clip_shadow: ^0.2.1
#   firebase_storage:
#   image_picker:
#   geolocator:
#   mapbox_gl: ^0.11.0
#   auth_buttons: ^0.0.6
#   modal_progress_hud: ^0.1.3
#   google_sign_in: ^4.5.9
#   flutter_launcher_icons: ^0.7.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
 

flutter_icons:    
  android: true   
  ios: true    
  image_path: "assets/images/forrest_tagger_icon.png" 
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sample_profile_image.jpg
    - assets/images/palm-tree-outline.png
    - assets/images/upload.png
    - assets/images/loading.gif

    