// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOsgQ-m9R9NkxFbxTBzZFuQ9FBNRc827w',
    appId: '1:281883850209:android:f6ba3c43d7f988b7fccea0',
    messagingSenderId: '281883850209',
    projectId: 'geo-quiz-70986',
    databaseURL: 'https://geo-quiz-70986-default-rtdb.firebaseio.com',
    storageBucket: 'geo-quiz-70986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcU_sLq5e7EPNWEDzn_mmWpsUFSMPItqA',
    appId: '1:281883850209:ios:eeff0d3b30a83633fccea0',
    messagingSenderId: '281883850209',
    projectId: 'geo-quiz-70986',
    databaseURL: 'https://geo-quiz-70986-default-rtdb.firebaseio.com',
    storageBucket: 'geo-quiz-70986.appspot.com',
    androidClientId: '281883850209-aljo7p8djqbhvd6pjij5ns2c79fndd47.apps.googleusercontent.com',
    iosClientId: '281883850209-tvnsrk8nkr7lufbtj5rjfbjblude19p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.forestTagger',
  );
}
